# Generated by Django 6.0.7 on 2026-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/')),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(blank=True, choices=[('X', 'X / Twitter'), ('Pixiv', 'Pixiv'), ('Instagram', 'Instagram'), ('Threads', 'Threads'), ('Bilibili', 'Bilibili'), ('Other', 'Other')], max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='artworks', to='museum.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
