# Generated by Django 6.0.7 on 2026-07-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='platform',
            field=models.CharField(blank=True, choices=[('X', 'X / Twitter'), ('Pixiv', 'Pixiv'), ('Instagram', 'Instagram'), ('Threads', 'Threads'), ('Bilibili', 'Bilibili'), ('米畫師', '米畫師'), ('小紅書', '小紅書'), ('Pinterest', 'Pinterest'), ('Other', 'Other')], max_length=20),
        ),
    ]
