# Generated by Django 6.0.7 on 2026-07-19 12:41

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_alter_artwork_platform'),
    ]

    operations = [
        VectorExtension(),  # CREATE EXTENSION IF NOT EXISTS vector
        migrations.AddField(
            model_name='artwork',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
