# Generated by Django 6.0.7 on 2026-07-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_artwork_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='source_url',
        ),
    ]
